version: '3'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgress:root@database:5432/postgres

  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
